name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Sufficient for full test suite
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
    
    - name: Lint and typecheck
      run: |
        bun run lint
        bun run typecheck
    
    - name: Build project
      run: bun run build
    
    - name: Make test scripts executable
      run: chmod +x tests/test-runner.sh
    
    - name: Run comprehensive test suite
      run: |
        echo "Starting unified test suite..."
        # Run full mode for comprehensive CI validation
        # This includes 4 core scenarios + individual template testing
        ./tests/test-runner.sh --mode=full
        # 
        # Optional: Add Playwright browser tests (increases CI time)
        # ./tests/test-runner.sh --mode=full --playwright
    
    - name: Upload test artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: |
          /tmp/bun-scaffolder-test/
          /tmp/*.log
        retention-days: 3
    
    - name: Upload Playwright report on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: |
          tests/playwright-report/
          test-results.json
        retention-days: 7
    
    - name: Test summary
      if: always()
      run: |
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        echo "✅ Unified test suite completed" >> $GITHUB_STEP_SUMMARY
        echo "- 4 Core scenarios (All packages + UI-only × Prisma/Drizzle)" >> $GITHUB_STEP_SUMMARY
        echo "- Individual template validation (10 templates)" >> $GITHUB_STEP_SUMMARY
        echo "- Code quality checks (TypeScript, lint, build)" >> $GITHUB_STEP_SUMMARY
        echo "- E2E server functionality tests" >> $GITHUB_STEP_SUMMARY
        echo "- Comprehensive integration testing" >> $GITHUB_STEP_SUMMARY
