name: Release

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "templates/**"
      - "scripts/**"
      - "tests/**"
      - "playwright.config.ts"
      - "package.json"
      - "bun.lockb"
      - "tsconfig.json"
      - "biome.json"
      - ".changeset/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # Call the CI workflow first to ensure all tests pass
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    needs: ci
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Install dependencies for templates
        run: bun install --cwd=templates

      - name: Run Type Check
        run: bun run typecheck

      - name: Run Linting
        run: bun run lint

      - name: Build Package
        run: bun run build

      - name: Release
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run changeset:version
          publish: bun run release
          title: "Version Packages"
          commit: "Version Packages"
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
